# Generated by Django 4.1.7 on 2023-03-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('citys', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('photo', models.ImageField(upload_to='user_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
