# Generated by Django 4.1.7 on 2023-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upl_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('insta', models.CharField(max_length=300)),
                ('fb', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('photo', models.ImageField(upload_to='user_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
