# Generated by Django 4.1.7 on 2023-03-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_upl_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='upl_image',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
