# Generated by Django 4.1.7 on 2023-03-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_upl_image_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upl_image',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='upl_image',
            name='email',
        ),
        migrations.RemoveField(
            model_name='upl_image',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='upl_image',
            name='insta',
        ),
        migrations.RemoveField(
            model_name='upl_image',
            name='phone',
        ),
        migrations.AddField(
            model_name='upl_image',
            name='aboutart',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upl_image',
            name='aboutyou',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upl_image',
            name='artype',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upl_image',
            name='socialmedia',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upl_image',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upl_image',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
