# Generated by Django 4.1.7 on 2023-03-31 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_upl_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upl_image',
            name='user',
        ),
        migrations.AlterField(
            model_name='upl_image',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
